image_size: [ 640,640 ]
iter_max: 500
num_classes: 20  #分类个数 + 1，因为使用多分类交叉熵


# ------------- 模型 -------------
model:
  freeze:
    start: 1 # 我们的框架默认 epoch 1 开始 , -1 不冻结
    end: 30 # -1 不解冻
  weights:
    checkpoints: './checkpoints/checkpoint1.pth'
    resume: './weight/model_epoch_70_loss_0.06909036442637444_.pth'


#  ------------- 优化器 -------------
adam:
  betas: [ 0.9, 0.999 ]

sgd:
  momentum: 0.937

solver:
  lr: 0.01
  weight_decay: 0.0005


warmup:
  warmup_method: 'linear'
  warmup_iters: 3
  warmup_factor: 0.1

anchors:
  - [ 10,13 , 16,30 , 33,23 ]
  - [ 30,61 , 62,45 , 59,119 ]
  - [ 116,90 , 156,198 , 373,326 ]

weight:
  device: 'cpu'


train:
  dataset:
    path: 'D:\dataset\VOC2007'
  batch_size: 16
  device: 'cuda'

val:
  dataset:
    path: 'D:\dataset\VOC2007'
  batch_size: 16


test:
  dataset:
    path: './data/voctest.txt'
    root: 'D:\dataset\VOC2007\JPEGImages'
  batch_size: 5
  device: 'cuda'

log_info:
  path: './logs'
  num: 4


